//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public int Id { get; set; }
        public string Full_name_perfomer { get; set; }
        public int IdAccountType { get; set; }
        public string Image { get; set; }
    
        public virtual AccountType AccountType { get; set; }
    }
}
