//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implementation_order
    {
        public string Full_name_performer { get; set; }
        public int Id_order { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Performer Performer { get; set; }
    }
}
