//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordering_accessories
    {
        public int Id_order { get; set; }
        public int Id_accessories { get; set; }
        public bool Order_status { get; set; }
    
        public virtual Accessories Accessories { get; set; }
        public virtual Order Order { get; set; }
    }
}
